### ISSUE TITLE
Can I use this in a browser?

### ISSUE THREAD

**Issue by Regenhardt** [nadavrot/layout#17]
So it seems rust can easily be compiled to WebAssembly, at least that's what I read. Is there anything stopping me from throwing this in a compiler and having it generate an svg in the browser by throwing my dot source into the module? I don't really understand how to build or integrate WASM yet, this is like my first try of understanding that.

**Comment by barafael** [comment]
Apparently, you can.

See this demo: https://barafael.github.io/wasm-dot-renderer/

Code is here: https://github.com/barafael/wasm-dot-renderer

Please close the issue if this answers your question.

**Comment by Regenhardt** [comment]
Ha nice, thanks a lot!
