### ISSUE TITLE
Color parsing is incorrect for rgba hexes

### ISSUE THREAD

**Issue by epsilon-phase** [nadavrot/layout#32]
Hi, I've been writing an application with egui that uses this to layout a graph.

So far most everything is pretty easy to work with, however, your color parsing code handles rgba incorrectly.

Specifically, if I have a color `#191d1dff`, it gets turned into `#1d1dffff` because it gets extended with full opacity

**Comment by nadavrot** [comment]
Thank you for fixing the issue!
