### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pnkfelix** [nadavrot/layout#6]
What license is the code being published under?

I suspect a related question will be: How much of it was developed via inspection of the original graphviz code? (That may make it subject to the license for *that code*, which is presented [here](https://graphviz.org/license/); that document says it uses "The Common Public License Version 1.0" that was produced from the Eclipse project.)

**Comment by nilslice** [comment]
@nadavrot - any chance you'd be open to a LICENSE here? I'll open a PR using MIT in case you agree to use it. I'd like to use this, but can't right now.

**Comment by KOLANICH** [comment]
Microsoft Automatic Graph Layout is a permissively licensed C# library, among one of algos in it is Siguyama algo used in GraphViz - one of the most complex and essential parts of the tool. So it may make sense to rewrite that part in Rust and reuse within this tool, if it is derived from GraphViz source code.

**Comment by nadavrot** [comment]
@nilslice 

Okay. Let's do it.

**Comment by pnkfelix** [comment]
Awesome, looks to me like https://github.com/nadavrot/layout/commit/b84f7d3f7322778b8e0fc3b0246096a5acb14c0e resolves this issue!
